server:
  port: 9999
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/drools
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    url: jdbc:mysql://localhost:3306/drools
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/xml/*.xml